### ISSUE TITLE
PyPI releases

### ISSUE THREAD

**Issue by AlecThomson** [lofar-astron/RMextract#57]
Hi @maaijke @gmloose ,

With the recent changes going into RMextract, will there be new releases onto PyPI? The last release is from 2021 it seems.

It may be neat to setup some CI/CD tools to automatically release new versions onto PyPI, if desired. I can help to get those implemented if that'd be useful.

**Comment by gmloose** [comment]
That is definitely the intention, yes. I leave it to @maaijke to decide when she thinks it's the proper time to do so. Some extra hands to help with automation would be welcomed very much. I sometimes struggle to find the time 😄.

**Comment by gmloose** [comment]
OK, I've put it on the top of my to-do list.

**Comment by AlecThomson** [comment]
Since RMextract now uses a modern `pyproject.toml` we could use the [Poetry Publish](https://github.com/marketplace/actions/publish-python-poetry-package) GitHub action to publish to PyPI automatically.

Actions like this require two manual steps:

1. Setting the appropriate version in the `pyproject.toml`. Right now I can't see where this is specified. Normally I would expect to see `version = "xxx"` - am I missing it somewhere?
2. Releasing on GitHub. This will trigger the action itself. The action will fail if the version already exists on PyPI, hence the need for step 1.

There will also be the need to set a repo secret `PYPI_TOKEN` with the appropriate value.

I've recently been using config like this:

```yaml
name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
```
Which triggers when a release with the tag `"v*.*.*"` is made. I note some of the releases haven't used this SemVer schema.

Let me know what you think and I can start a PR :)
